export const mockReels = [
  {
    id: "1",
    title: "React Hooks Explained in 60 Seconds",
    description:
      "Learn the basics of React Hooks with this quick tutorial. Perfect for beginners who want to understand useState and useEffect! #React #WebDev #Programming",
    video_url: "https://www.pexels.com/video/two-men-sitting-by-the-river-bank-while-talking-to-each-other-4830364/",
    creator: {
      username: "reactmaster",
      full_name: "Sarah Johnson",
      avatar_url: "/placeholder.svg?height=40&width=40&text=SJ",
    },
    like_count: 1250,
    comment_count: 89,
    view_count: 15600,
  },
  {
    id: "2",
    title: "CSS Grid Layout Tricks",
    description:
      "Master CSS Grid with these amazing layout tricks! Create responsive designs that look great on any device. #CSS #WebDesign #Frontend",
    video_url: "https://www.pexels.com/video/a-reel-to-reel-tape-recorder-spinning-8382685/",
    creator: {
      username: "cssqueen",
      full_name: "Emma Davis",
      avatar_url: "/placeholder.svg?height=40&width=40&text=ED",
    },
    like_count: 2100,
    comment_count: 156,
    view_count: 28900,
  },
  {
    id: "3",
    title: "JavaScript ES6 Features You Must Know",
    description:
      "Discover the most important ES6 features that every JavaScript developer should master. Arrow functions, destructuring, and more! #JavaScript #ES6 #WebDev",
    video_url: "https://www.pexels.com/video/people-camping-on-frozen-lake-6831465/",
    creator: {
      username: "jsninjas",
      full_name: "Alex Rivera",
      avatar_url: "/placeholder.svg?height=40&width=40&text=AR",
    },
    like_count: 3400,
    comment_count: 234,
    view_count: 45200,
  },
  {
    id: "4",
    title: "Python Data Science Basics",
    description:
      "Get started with data science using Python! Learn pandas, numpy, and matplotlib in this quick introduction. #Python #DataScience #Analytics",
    video_url: "https://www.pexels.com/video/two-men-sitting-by-the-river-fishing-4830314/",
    creator: {
      username: "datascientist",
      full_name: "Dr. Michael Chen",
      avatar_url: "/placeholder.svg?height=40&width=40&text=MC",
    },
    like_count: 1890,
    comment_count: 167,
    view_count: 22300,
  },
  {
    id: "5",
    title: "UI/UX Design Principles",
    description:
      "Learn the fundamental principles of great UI/UX design. Color theory, typography, and user experience best practices! #Design #UIUX #Creative",
    video_url: "/placeholder.svg?height=800&width=450&text=UI+UX+Design+Video",
    creator: {
      username: "designpro",
      full_name: "Maya Patel",
      avatar_url: "/placeholder.svg?height=40&width=40&text=MP",
    },
    like_count: 2750,
    comment_count: 198,
    view_count: 31800,
  },
]

export const mockCourses = [
  {
    id: "1",
    title: "Complete React Development Course",
    description: "Master React from basics to advanced concepts. Build real-world projects and become a React expert.",
    thumbnail_url: "/placeholder.svg?height=200&width=300&text=React+Course",
    price: 89.99,
    original_price: 149.99,
    category: "Programming",
    level: "Intermediate",
    language: "English",
    duration_hours: 12,
    duration_minutes: 30,
    instructor: {
      username: "reactmaster",
      full_name: "Sarah Johnson",
      avatar_url: "/placeholder.svg?height=40&width=40&text=SJ",
    },
    rating: 4.9,
    student_count: 12500,
    lesson_count: 45,
    what_you_learn: [
      "Build modern React applications",
      "Master React Hooks and Context API",
      "Create responsive user interfaces",
      "Deploy React apps to production",
    ],
    requirements: ["Basic JavaScript knowledge", "HTML and CSS fundamentals", "A computer with internet connection"],
    target_audience: [
      "Beginner to intermediate developers",
      "Anyone wanting to learn React",
      "Frontend developers looking to upskill",
    ],
  },
  {
    id: "2",
    title: "UI/UX Design Masterclass",
    description: "Learn professional UI/UX design from industry experts. Create stunning designs that users love.",
    thumbnail_url: "/placeholder.svg?height=200&width=300&text=Design+Course",
    price: 79.99,
    original_price: 129.99,
    category: "Design",
    level: "Beginner",
    language: "English",
    duration_hours: 8,
    duration_minutes: 45,
    instructor: {
      username: "designpro",
      full_name: "Maya Patel",
      avatar_url: "/placeholder.svg?height=40&width=40&text=MP",
    },
    rating: 4.8,
    student_count: 8900,
    lesson_count: 32,
    what_you_learn: [
      "Design principles and theory",
      "User research and personas",
      "Wireframing and prototyping",
      "Design systems and components",
    ],
    requirements: [
      "No prior design experience needed",
      "Access to design software (Figma recommended)",
      "Creative mindset and willingness to learn",
    ],
    target_audience: [
      "Aspiring UI/UX designers",
      "Developers wanting to learn design",
      "Career changers interested in design",
    ],
  },
  {
    id: "3",
    title: "Digital Marketing Strategy",
    description: "Master digital marketing with proven strategies. Learn SEO, social media, and content marketing.",
    thumbnail_url: "/placeholder.svg?height=200&width=300&text=Marketing+Course",
    price: 69.99,
    original_price: 119.99,
    category: "Marketing",
    level: "Advanced",
    language: "English",
    duration_hours: 10,
    duration_minutes: 15,
    instructor: {
      username: "marketingguru",
      full_name: "David Kim",
      avatar_url: "/placeholder.svg?height=40&width=40&text=DK",
    },
    rating: 4.7,
    student_count: 15200,
    lesson_count: 38,
    what_you_learn: [
      "SEO and content marketing",
      "Social media advertising",
      "Email marketing campaigns",
      "Analytics and conversion optimization",
    ],
    requirements: [
      "Basic understanding of business",
      "Access to social media platforms",
      "Willingness to experiment and test",
    ],
    target_audience: [
      "Business owners and entrepreneurs",
      "Marketing professionals",
      "Anyone wanting to grow online presence",
    ],
  },
]

export const mockCategories = [
  { id: "1", name: "Technology", description: "Latest tech trends", icon: "⚡", color: "#3B82F6" },
  { id: "2", name: "Programming", description: "Coding tutorials", icon: "💻", color: "#10B981" },
  { id: "3", name: "Design", description: "UI/UX and creative design", icon: "🎨", color: "#8B5CF6" },
  { id: "4", name: "Business", description: "Entrepreneurship and marketing", icon: "💼", color: "#F59E0B" },
  { id: "5", name: "Education", description: "Learning and academic content", icon: "🎓", color: "#6366F1" },
  { id: "6", name: "Health", description: "Fitness and wellness", icon: "💪", color: "#EF4444" },
]
